[package]
name = "rust_roguelike"
version = "0.1.0"
authors = ["Mickael <mickael.spilmont.fr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15"